
import { CommunityState } from "@/src/atoms/communitiesAtoms";
import { About } from "@/src/components/Community/About";
import PageContent from "@/src/components/Layout/PageContent";
import NewPostForm from "@/src/components/Posts/NewPostForm";
import { auth } from "@/src/firebase/clientApp";
import { Box, Text } from "@chakra-ui/react";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useAuthState } from "react-firebase-hooks/auth";
import { useRecoilState, useRecoilValue } from "recoil";

const SubmitPostPage: React.FC = () => {
  const router = useRouter();
  const { communityId, selectedTab } = router.query;
  const [user] = useAuthState(auth);
  const communityStateValue = useRecoilValue(CommunityState);
  console.log("community state value", communityStateValue);
  return (
    <>
      <Head>
        <title>Submit to {communityId as string}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/redditFace.svg" />
      </Head>
      <PageContent>
        <>
          <Box p="14px 0px" borderBottom="1px solid" borderColor="white">
            <Text>Create a post</Text>
          </Box>
          {user && (
            <NewPostForm
              selected={selectedTab as string}
              user={user}
              community={communityId as string}
              communityImageURL={communityStateValue.currentCommunity.imageURL as string}
            />
          )}
        </>
        <>
          {communityStateValue.currentCommunity && (
            <About
              onCreatePage={true}
              communityData={communityStateValue.currentCommunity}
            />
          )}
        </>
      </PageContent>
    </>
  );
};

export default SubmitPostPage;
